[package]
name = "rust-snippet"
publish = false
edition = "2024"
rust-version = "1.85"

[dependencies]
nalgebra = "0.34"
num-complex = "0.4"
qomo = "0.0.8"
tfhe-fft = { version = "*" }
tfhe = { version = "*", features = [
  "boolean",
  "shortint",
  "integer"
] }
